name: build

on: [pull_request]

jobs:
  setup:
    name: setup
    runs-on: ubuntu-18.04
    steps:
      - name: checking out
        uses: actions/checkout@v2
      - name: install
        run: |
          rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
          rustup component add clippy

      - name: async-std
        run: |
          cd /home/runner/work/greeter/greeter/greeter-async-std
          cargo clippy -- -D warnings
          cargo test --verbose --all
          cargo fmt -- --check

      - name: glommio
        run: |
          cd /home/runner/work/greeter/greeter/greeter-glommio
          cargo clippy -- -D warnings
          cargo test --verbose --all
          cargo fmt -- --check

      - name: minimum
        run: |
          cd /home/runner/work/greeter/greeter/greeter-minimum
          cargo clippy -- -D warnings
          cargo test --verbose --all
          cargo fmt -- --check

      - name: smol
        run: |
          cd /home/runner/work/greeter/greeter/greeter-smol
          cargo clippy -- -D warnings
          cargo test --verbose --all
          cargo fmt -- --check

      - name: tokio
        run: |
          cd /home/runner/work/greeter/greeter/greeter-tokio
          cargo clippy -- -D warnings
          cargo test --verbose --all
          cargo fmt -- --check

      - name: noasync
        run: |
          cd /home/runner/work/greeter/greeter/greeter-noasync
          cargo clippy -- -D warnings
          cargo test --verbose --all
          cargo fmt -- --check
